apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: angular
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: angular
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
