name: Deployment-CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '19'

    - name: install npm
      run: npm install -g @angular/cli  --force
      
    - name: Build the Docker image
      run: |
        docker build -t  angular-app:v1 .
        docker tag angular-app:v1 smritidn6docker/angular-app:v1
       
